version: '2'

services:
    db:
        image: postgres
        container_name: db
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - TZ=Europe/Paris
        volumes:
          - ./bdd:/docker-entrypoint-initdb.d/
        ports:
          - "5432:5432"

    app:
        image: 'goraphe'
        build:
          context: .
        container_name: app
        depends_on:
          - db
        env_file:
          .env
        ports:
          - "80:8080"
        volumes:
          - ./scripts:/scripts/

    pgadmin:
        container_name: phadmin
        image: dpage/pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: root@root.root
          PGADMIN_DEFAULT_PASSWORD: root
        ports:
          - "5050:80"

